package com.john.blog.website.model.Vo;

import java.io.Serializable;

public class AudiosVo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_audios.uid
     *
     * @mbggenerated
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_audios.singer
     *
     * @mbggenerated
     */
    private String singer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_audios.songname
     *
     * @mbggenerated
     */
    private String songname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_audios.src
     *
     * @mbggenerated
     */
    private String src;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_audios
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_audios.uid
     *
     * @return the value of t_audios.uid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_audios.uid
     *
     * @param uid the value for t_audios.uid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_audios.singer
     *
     * @return the value of t_audios.singer
     *
     * @mbggenerated
     */
    public String getSinger() {
        return singer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_audios.singer
     *
     * @param singer the value for t_audios.singer
     *
     * @mbggenerated
     */
    public void setSinger(String singer) {
        this.singer = singer == null ? null : singer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_audios.songname
     *
     * @return the value of t_audios.songname
     *
     * @mbggenerated
     */
    public String getSongname() {
        return songname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_audios.songname
     *
     * @param songname the value for t_audios.songname
     *
     * @mbggenerated
     */
    public void setSongname(String songname) {
        this.songname = songname == null ? null : songname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_audios.src
     *
     * @return the value of t_audios.src
     *
     * @mbggenerated
     */
    public String getSrc() {
        return src;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_audios.src
     *
     * @param src the value for t_audios.src
     *
     * @mbggenerated
     */
    public void setSrc(String src) {
        this.src = src == null ? null : src.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_audios
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AudiosVo other = (AudiosVo) that;
        return (this.getUid() == null ? other.getUid() == null : this.getUid().equals(other.getUid()))
            && (this.getSinger() == null ? other.getSinger() == null : this.getSinger().equals(other.getSinger()))
            && (this.getSongname() == null ? other.getSongname() == null : this.getSongname().equals(other.getSongname()))
            && (this.getSrc() == null ? other.getSrc() == null : this.getSrc().equals(other.getSrc()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_audios
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUid() == null) ? 0 : getUid().hashCode());
        result = prime * result + ((getSinger() == null) ? 0 : getSinger().hashCode());
        result = prime * result + ((getSongname() == null) ? 0 : getSongname().hashCode());
        result = prime * result + ((getSrc() == null) ? 0 : getSrc().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_audios
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", uid=").append(uid);
        sb.append(", singer=").append(singer);
        sb.append(", songname=").append(songname);
        sb.append(", src=").append(src);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}