package com.john.blog.website.dao;


import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.john.blog.website.model.Vo.AudiosVo;
import com.john.blog.website.model.Vo.AudiosVoExample;

public interface AudiosVoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_audios
     *
     * @mbggenerated
     */
    int countByExample(AudiosVoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_audios
     *
     * @mbggenerated
     */
    int deleteByExample(AudiosVoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_audios
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_audios
     *
     * @mbggenerated
     */
    int insert(AudiosVo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_audios
     *
     * @mbggenerated
     */
    int insertSelective(AudiosVo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_audios
     *
     * @mbggenerated
     */
    List<AudiosVo> selectByExample(AudiosVoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_audios
     *
     * @mbggenerated
     */
    AudiosVo selectByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_audios
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AudiosVo record, @Param("example") AudiosVoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_audios
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AudiosVo record, @Param("example") AudiosVoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_audios
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AudiosVo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_audios
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AudiosVo record);
}